# Generated by Django 5.1.3 on 2024-12-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_plant_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='dummy_field',
        ),
        migrations.AddField(
            model_name='service',
            name='dummy_field',
            field=models.BooleanField(default=False),
        ),
    ]
