# Generated by Django 5.1.3 on 2024-12-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_plant_dummy_field_service_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='dummy_field',
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
    ]
